# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\A\PycharmProjects\ImgToTxtApp\ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(385, 345)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: #22222e\n"
                                 "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 391, 121))
        self.frame.setStyleSheet("background-color: #69ffd4")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(140, 50, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: transparent;\n"
                                 "color:white")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(130, 40, 141, 51))
        self.label_3.setStyleSheet("background-color: #11111e;\n"
                                   "color: #11111e;\n"
                                   "border: 3px solid #00b581;\n"
                                   "\n"
                                   "")
        self.label_3.setObjectName("label_3")
        self.label_3.raise_()
        self.label.raise_()
        self.output_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.output_text.setGeometry(QtCore.QRect(10, 210, 221, 111))
        self.output_text.setStyleSheet("background-color: #11111e;\n"
                                       "border: 2px solid #00ffb6;\n"
                                       "color: white")
        self.output_text.setObjectName("output_text")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 130, 221, 80))
        self.groupBox.setStyleSheet("background-color: #22222e;\n"
                                    "border: 0px solid #00ffb6;\n"
                                    "color: white")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.img_loc_edit = QtWidgets.QLineEdit(self.groupBox)
        self.img_loc_edit.setGeometry(QtCore.QRect(0, 50, 221, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(True)
        font.setWeight(75)
        self.img_loc_edit.setFont(font)
        self.img_loc_edit.setStyleSheet("background-color: #11111e;\n"
                                        "border: 2px solid #00ffb6;\n"
                                        "color: white")
        self.img_loc_edit.setText("")
        self.img_loc_edit.setObjectName("img_loc_edit")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(0, 20, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Meiryo")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: #11111e;\n"
                                   "border: 2px solid #00ffb6;\n"
                                   "color: white")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.load_img_button = QtWidgets.QPushButton(self.groupBox)
        self.load_img_button.setGeometry(QtCore.QRect(120, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.load_img_button.setFont(font)
        self.load_img_button.setStyleSheet("QPushButton{\n"
                                           "    background-color: #11111e;\n"
                                           "    border: 2px solid #00ffb6;\n"
                                           "    color: white;\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton:pressed{\n"
                                           "    background-color: #00ffb6;\n"
                                           "    border: 2px solid #00a878;    \n"
                                           "    color: black\n"
                                           "}")
        self.load_img_button.setObjectName("load_img_button")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(100, 20, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: white;\n"
                                   "background-color: transparent")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(260, 200, 101, 121))
        self.groupBox_2.setStyleSheet("background-color: #22222e;\n"
                                      "border: 0px solid #00ffb6;\n"
                                      "color: white")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(30, 0, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Meiryo")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: #11111e;\n"
                                   "border: 2px solid #00ffb6;\n"
                                   "color: white")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.convert_button = QtWidgets.QPushButton(self.groupBox_2)
        self.convert_button.setGeometry(QtCore.QRect(0, 90, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.convert_button.setFont(font)
        self.convert_button.setStyleSheet("QPushButton{\n"
                                          "    background-color: #11111e;\n"
                                          "    border: 2px solid #00ffb6;\n"
                                          "    color: white;\n"
                                          "}\n"
                                          "\n"
                                          "QPushButton:pressed{\n"
                                          "    background-color: #00ffb6;\n"
                                          "    border: 2px solid #00a878;    \n"
                                          "    color: black\n"
                                          "}")
        self.convert_button.setObjectName("convert_button")
        self.language_cbox = QtWidgets.QComboBox(self.groupBox_2)
        self.language_cbox.setGeometry(QtCore.QRect(0, 20, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.language_cbox.setFont(font)
        self.language_cbox.setStyleSheet("background-color: #11111e;\n"
                                         "border: 2px solid #00ffb6;\n"
                                         "color: white")
        self.language_cbox.setObjectName("language_cbox")
        self.language_cbox.addItem("")
        self.language_cbox.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ImgTotxt"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "Image location"))
        self.load_img_button.setText(_translate("MainWindow", "Load image"))
        self.label_5.setText(_translate("MainWindow", "or"))
        self.label_2.setText(_translate("MainWindow", "Language"))
        self.convert_button.setText(_translate("MainWindow", "Convert"))
        self.language_cbox.setItemText(0, _translate("MainWindow", "English"))
        self.language_cbox.setItemText(1, _translate("MainWindow", "Russian"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
